[iterm2]
recommend = 0
description = "https://iterm2.com/downloads.html"

[vscode]
recommend = 0
description = "https://code.visualstudio.com/download"

[hammerspoon]
recommend = 0
description="https://www.hammerspoon.org/"

# -----------------------------

[zsh]
recommend = 0
install = 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
post = "./zsh/post.sh"

[colima]
recommend = 0
install = "brew install colima"

[docker]
recommend = 0
install = "brew install docker docker-compose"
