#!/bin/zsh

function get_git_remote_urls() {
    local dir="$1"
    local indent="$2"

    # ignore path to project_*
    if [[ "$dir" =~ "project_" ]]; then
        return
    fi

    # 遍历子文件夹
    for subdir in "$dir"/*; do
        # 检查子文件夹是否为目录

        if [ -d "$subdir" ]; then
            # 进入子文件夹
            cd "$subdir" || continue

            # 检查是否为 Git 仓库
            if [ -d .git ]; then
                # 获取 Git 远程 URL
                remote_url=$(git remote get-url origin 2>/dev/null)
                
                if [ $? -ne 0 ]; then
                    cd -
                    continue
                fi

                # ignore if no remote_url
                if [ -z "$remote_url" ]; then
                    cd -
                    continue
                fi

                # 输出结果
                # 执行 shell 命令
                # echo "git submodule add -f $remote_url $subdir"
                rm -rf $subdir

                # echo "[submodule \"$subdir\"]"
	            # echo "    path = $subdir"
	            # echo "    url = $remote_url"

                cd -
            else
                # echo "not git repo, next dir"
                cd -

                # 递归处理子文件夹
                get_git_remote_urls "$subdir" "${indent}  "
            fi
        fi
    done
}

# 调用函数，传入顶级目录
get_git_remote_urls "workspaces" ""

