#!/bin/bash

## this hook is used to check if there is any sensitive information in the commit.
## especially for the project which is open source.

sensitive_patterns=(
  "sensitive_info1"
  "sensitive_info2"
  "sensitive_info3"
  "sensitive_info4"
)

exclude_paths=(
  $(eval echo "~/your/private/project")
)

# Skip hooks for exclude paths
current_path=$(pwd)

for path in "${exclude_paths[@]}"; do
  if [[ "$current_path" == $path* ]]; then
    echo "✅ Skip: No check for internal projects."
    exit 0
  fi
done

# Loop through the files in the commit
for file in $(git diff --cached --name-only)
do
  # Check each line of the file for sensitive patterns
  for pattern in "${sensitive_patterns[@]}"
  do
    if git show ":$file" | grep -q "$pattern"
    then
      echo "🚫 Error: Sensitive information found in $file:"
      git show ":$file" | grep -n "$pattern"
      exit 1
    fi
  done
done

echo "✅ Pass: No sensitive information found."

exit 0
